### ISSUE TITLE
[Suggestion] Reimplement Blacklist, embed client side messages and sort order functionality

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Skullbite/powercord-e621#2]
I was looking through some of the code of the plugin and noticed a bit of unused stuff that either sorta work or don't work at all.

Something that works is the embed format, but the image doesn't show. Give it the usual e621 embed format and maybe it could be a toggle option in the settings?
![image](https://user-images.githubusercontent.com/45246118/100964411-91581480-34f6-11eb-94ad-8da46d550318.png)

And stuff that simply doesn't work, but still show up are the additional settings. These don't function, but they would be super handy to the user if they did work.
![image](https://user-images.githubusercontent.com/45246118/100964429-9d43d680-34f6-11eb-86da-51841b91b59c.png)

Are there plans to add these in later? And if not, could they be added in the future?
The blacklist especially would be useful.

**Comment by Skullbite** [comment]
1. The blacklist is on my to do list, I just haven't found the time to do it.
2. Local messages don't load previews which is why I scrapped the embed. I will see if I can implement a modal to see that could preview the image rather than a message. 

Just let me see what I can do.

**Comment by Mr-Foxtrot** [comment]
Alrighty, thanks for making the plugin Skullbite!

**Comment by Mr-Foxtrot** [comment]
Got the update, the new sorting settings and post modal are working great!

**Comment by Skullbite** [comment]
Good to hear! With [this](https://github.com/Skullbite/powercord-e621/commit/34ea0f315cbb731f900e14272a0d64a50c7088c1) commit, I consider this issue resolved.
